# Generated by Django 5.2.7 on 2025-10-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Driver, 7 Iron, Pitching Wedge', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GolfRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('course_name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField(help_text='Distance in yards')),
                ('shot_shape', models.CharField(choices=[('Straight', 'Straight'), ('Fade', 'Fade'), ('Draw', 'Draw'), ('Slice', 'Slice'), ('Hook', 'Hook')], max_length=10)),
                ('lie', models.CharField(choices=[('Fairway', 'Fairway'), ('Rough', 'Rough'), ('Sand', 'Sand'), ('Tee Box', 'Tee Box')], max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.club')),
                ('golf_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.golfround')),
            ],
        ),
    ]
