# Generated by Django 5.2.7 on 2025-11-12 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchMonitorImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('Garmin R10', 'Garmin R10'), ('SkyTrak+', 'SkyTrak+'), ('Flightscope Mevo+', 'Flightscope Mevo+'), ('Arccos Caddie', 'Arccos Caddie'), ('Generic Launch Monitor', 'Generic Launch Monitor')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('raw_data', models.TextField(help_text='Original file content (JSON) for debugging')),
                ('parsed_data', models.JSONField(blank=True, help_text='Normalized parsed data', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('preview', 'Preview Ready'), ('imported', 'Imported'), ('failed', 'Failed'), ('partial', 'Partially Imported')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='Parsing errors and warnings')),
                ('rounds_created', models.PositiveIntegerField(default=0)),
                ('shots_created', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
